#include <QApplication>
#include "mainwindow.h"
#include <stdio.h>
#include "subnet_v6.h"
#include "subnet_v4.h"
#include <iostream>
#include <QtGlobal>
#include <QSysInfo>
#include <QStyleFactory>

// this include file contains just a preprocessor directive to store the current local node number
// of this source commit from mercurial. (COMMIT_NO) It is only used here.
// The file is generated by my mercurial setup on my main dev system. I prepped the hgrc to include the following:
//  [hooks]
//  pre-commit = echo "#define COMMIT_NO $(($(hg id -n)+1))" > ./generated_version.h
#include "generated_version.h"

int main(int argc, char *argv[])
{

   QApplication a(argc, argv);
   a.setOrganizationName("wolfchild.de");
   a.setOrganizationDomain("wolfchild.de");
   a.setApplicationName("SubnetMapper");
   a.setApplicationVersion("2.0."+QString::number(COMMIT_NO));
   QApplication::setStyle(QStyleFactory::create("Windows"));

   MainWindow w;
   w.show();

   return a.exec();
}
